### ISSUE TITLE
Creation handler to accept different kinds of model

### ISSUE THREAD

**Issue by lharland** [CesarValiente/KUnidirectional#12]
Can the creation handler used with another model other than Item?

**Comment by CesarValiente** [comment]
The creation handler just takes an action like the other handlers, in this case, `CreateAction` type, the action inside has the metadata to do what we need to do, in this case with `CreateItemAction` we have the metadata to build an item that will be stored.
Does this solve your question? if not, could you explain a bit more?

**Comment by CesarValiente** [comment]
Closing it since it seems the answer was enough.
